config/routes.rb
Rails.application.routes.draw do
  resources :crypto_coins
  root to: 'crypto_coins#home'
  get 'ltc', to: 'crypto_coins#ltc'
  get 'eth', to: 'crypto_coins#eth'
  get 'bch', to: 'crypto_coins#bch'
  get 'statsbtc', to: 'crypto_coins#statsbtc'
  get 'statsltc', to: 'crypto_coins#statsltc'
  get 'statseth', to: 'crypto_coins#statseth'
  get 'statsbch', to: 'crypto_coins#statsbch'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/crypto_coin.rb
class CryptoCoin < ApplicationRecord
end

app/controllers/crypto_coins_controller.rb
class CryptoCoinsController < ApplicationController
  require 'data_manager'

  before_action :set_crypto_coin, only: [:show, :edit, :update, :destroy]

  # GET /crypto_coins
  # GET /crypto_coins.json
  def index
    @crypto_coins = CryptoCoin.all
  end
  def home
    dm = DataManager.new
    @timestamps_bitfinex_nr = dm.get_last_btc_time_bitfinex("btcusd")
    @timestamps_bitfinex = dm.get_last_btc_time_bitfinex("btcusd").reverse
    @prices_bitfinex = dm.get_last_btc_price_bitfinex("btcusd")
    @prices_bitstamp = dm.get_last_btc_price_bitstamp("btcusd")
    @prices_buda = dm.get_last_btc_price_buda("btc-clp")
    sub = dm.substracted(@prices_bitfinex,@prices_buda,@prices_bitstamp)
    @last_prices_bitfinex_nr = sub[:x]
    @last_prices_buda_nr = sub[:y]
    @last_prices_bitstamp_nr = sub[:z]

    @last_prices_bitfinex = sub[:x].reverse
    @last_prices_buda = sub[:y].reverse
    @last_prices_bitstamp = sub[:z].reverse
    daily = dm.latest_day_hour("btcusd", "btc-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    @todobitfinex = dm.oscilator(@day_bitfinex)[:todo]
    @todobuda = dm.oscilator(@day_buda)[:todo]
    @todobitstamp= dm.oscilator(@day_bitstamp)[:todo]




  end
  def ltc
    dm = DataManager.new
    @timestamps_bitfinex_nr = dm.get_last_btc_time_bitfinex("ltcusd")
    @timestamps_bitfinex = dm.get_last_btc_time_bitfinex("ltcusd").reverse
    @prices_bitfinex = dm.get_last_btc_price_bitfinex("ltcusd")
    @prices_bitstamp = dm.get_last_btc_price_bitstamp("ltcusd")
    @prices_buda = dm.get_last_btc_price_buda("ltc-clp")
    sub = dm.substracted(@prices_bitfinex,@prices_buda,@prices_bitstamp)
    @last_prices_bitfinex_nr = sub[:x]
    @last_prices_buda_nr = sub[:y]
    @last_prices_bitstamp_nr = sub[:z]

    @last_prices_bitfinex = sub[:x].reverse
    @last_prices_buda = sub[:y].reverse
    @last_prices_bitstamp = sub[:z].reverse
    daily = dm.latest_day_hour("ltcusd", "ltc-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    @todobitfinex = dm.oscilator(@day_bitfinex)[:todo]
    @todobuda = dm.oscilator(@day_buda)[:todo]
    @todobitstamp= dm.oscilator(@day_bitstamp)[:todo]

  end
  def statsbtc
    dm = DataManager.new
    daily = dm.latest_day_hour("btcusd", "btc-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    sobitfinex = dm.oscilator(@day_bitfinex)
    sobbuda = dm.oscilator(@day_buda)
    sobitstamp = dm.oscilator(@day_bitstamp)
    @kbitfinex = sobitfinex[:k]
    @sbitfinex = sobitfinex[:s]
    @medbitfinex = sobitfinex[:media]
    @soldbitfinex = sobitfinex[:sold]
    @buybitfinex = sobitfinex[:buy]

    @kbitstamp = sobitstamp[:k]
    @sbitstamp = sobitstamp[:s]
    @medbitstamp = sobitstamp[:media]
    @soldbitstamp = sobitstamp[:sold]
    @buybitstamp = sobitstamp[:buy]

    @kbuda = sobbuda[:k]
    @sbuda = sobbuda[:s]
    @medbuda = sobbuda[:media]
    @soldbuda = sobbuda[:sold]
    @buybuda = sobbuda[:buy]
  end
  def statsltc
    dm = DataManager.new
    daily = dm.latest_day_hour("ltcusd", "ltc-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    sobitfinex = dm.oscilator(@day_bitfinex)
    sobbuda = dm.oscilator(@day_buda)
    sobitstamp = dm.oscilator(@day_bitstamp)
    @kbitfinex = sobitfinex[:k]
    @sbitfinex = sobitfinex[:s]
    @medbitfinex = sobitfinex[:media]
    @soldbitfinex = sobitfinex[:sold]
    @buybitfinex = sobitfinex[:buy]

    @kbitstamp = sobitstamp[:k]
    @sbitstamp = sobitstamp[:s]
    @medbitstamp = sobitstamp[:media]
    @soldbitstamp = sobitstamp[:sold]
    @buybitstamp = sobitstamp[:buy]

    @kbuda = sobbuda[:k]
    @sbuda = sobbuda[:s]
    @medbuda = sobbuda[:media]
    @soldbuda = sobbuda[:sold]
    @buybuda = sobbuda[:buy]
  end
  def statseth
    dm = DataManager.new
    daily = dm.latest_day_hour("ethusd", "eth-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    sobitfinex = dm.oscilator(@day_bitfinex)
    sobbuda = dm.oscilator(@day_buda)
    sobitstamp = dm.oscilator(@day_bitstamp)
    @kbitfinex = sobitfinex[:k]
    @sbitfinex = sobitfinex[:s]
    @medbitfinex = sobitfinex[:media]
    @soldbitfinex = sobitfinex[:sold]
    @buybitfinex = sobitfinex[:buy]

    @kbitstamp = sobitstamp[:k]
    @sbitstamp = sobitstamp[:s]
    @medbitstamp = sobitstamp[:media]
    @soldbitstamp = sobitstamp[:sold]
    @buybitstamp = sobitstamp[:buy]

    @kbuda = sobbuda[:k]
    @sbuda = sobbuda[:s]
    @medbuda = sobbuda[:media]
    @soldbuda = sobbuda[:sold]
    @buybuda = sobbuda[:buy]
  end
  def statsbch
    dm = DataManager.new
    daily = dm.latest_day_hour("bchusd", "bch-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    sobitfinex = dm.oscilator(@day_bitfinex)
    sobbuda = dm.oscilator(@day_buda)
    sobitstamp = dm.oscilator(@day_bitstamp)
    @kbitfinex = sobitfinex[:k]
    @sbitfinex = sobitfinex[:s]
    @medbitfinex = sobitfinex[:media]
    @soldbitfinex = sobitfinex[:sold]
    @buybitfinex = sobitfinex[:buy]

    @kbitstamp = sobitstamp[:k]
    @sbitstamp = sobitstamp[:s]
    @medbitstamp = sobitstamp[:media]
    @soldbitstamp = sobitstamp[:sold]
    @buybitstamp = sobitstamp[:buy]

    @kbuda = sobbuda[:k]
    @sbuda = sobbuda[:s]
    @medbuda = sobbuda[:media]
    @soldbuda = sobbuda[:sold]
    @buybuda = sobbuda[:buy]
  end
  def eth
    dm = DataManager.new
    @timestamps_bitfinex_nr = dm.get_last_btc_time_bitfinex("ethusd")
    @timestamps_bitfinex = dm.get_last_btc_time_bitfinex("ethusd").reverse
    @prices_bitfinex = dm.get_last_btc_price_bitfinex("ethusd")
    @prices_bitstamp = dm.get_last_btc_price_bitstamp("ethusd")
    @prices_buda = dm.get_last_btc_price_buda("eth-clp")
    sub = dm.substracted(@prices_bitfinex,@prices_buda,@prices_bitstamp)
    @last_prices_bitfinex_nr = sub[:x]
    @last_prices_buda_nr = sub[:y]
    @last_prices_bitstamp_nr = sub[:z]

    @last_prices_bitfinex = sub[:x].reverse
    @last_prices_buda = sub[:y].reverse
    @last_prices_bitstamp = sub[:z].reverse
    daily = dm.latest_day_hour("ethusd", "eth-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    @todobitfinex = dm.oscilator(@day_bitfinex)[:todo]
    @todobuda = dm.oscilator(@day_buda)[:todo]
    @todobitstamp= dm.oscilator(@day_bitstamp)[:todo]

  end
  def bch
    dm = DataManager.new
    @timestamps_bitfinex_nr = dm.get_last_btc_time_bitfinex("bchusd")
    @timestamps_bitfinex = dm.get_last_btc_time_bitfinex("bchusd").reverse
    @prices_bitfinex = dm.get_last_btc_price_bitfinex("bchusd")
    @prices_bitstamp = dm.get_last_btc_price_bitstamp("bchusd")
    @prices_buda = dm.get_last_btc_price_buda("bch-clp")
    sub = dm.substracted(@prices_bitfinex,@prices_buda,@prices_bitstamp)
    @last_prices_bitfinex_nr = sub[:x]
    @last_prices_buda_nr = sub[:y]
    @last_prices_bitstamp_nr = sub[:z]

    @last_prices_bitfinex = sub[:x].reverse
    @last_prices_buda = sub[:y].reverse
    @last_prices_bitstamp = sub[:z].reverse
    daily = dm.latest_day_hour("bchusd", "bch-clp")
    @day_bitfinex = daily[:x]
    @day_buda = daily[:y]
    @day_bitstamp = daily[:z]
    @day_timestamps = daily[:times]
    @todobitfinex = dm.oscilator(@day_bitfinex)[:todo]
    @todobuda = dm.oscilator(@day_buda)[:todo]
    @todobitstamp= dm.oscilator(@day_bitstamp)[:todo]
  end
  # GET /crypto_coins/1
  # GET /crypto_coins/1.json
  def show
  end

  # GET /crypto_coins/new
  def new
    @crypto_coin = CryptoCoin.new
=begin
    rd = ::ReadDataFromApiJob.new
    data = rd.read_from_api
    rd.save(data)
=end
  end

  # GET /crypto_coins/1/edit
  def edit
  end

  # POST /crypto_coins
  # POST /crypto_coins.json
  def create
    @crypto_coin = CryptoCoin.new(crypto_coin_params)

    respond_to do |format|
      if @crypto_coin.save
        format.html { redirect_to @crypto_coin, notice: 'Crypto coin was successfully created.' }
        format.json { render :show, status: :created, location: @crypto_coin }
      else
        format.html { render :new }
        format.json { render json: @crypto_coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crypto_coins/1
  # PATCH/PUT /crypto_coins/1.json
  def update
    respond_to do |format|
      if @crypto_coin.update(crypto_coin_params)
        format.html { redirect_to @crypto_coin, notice: 'Crypto coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto_coin }
      else
        format.html { render :edit }
        format.json { render json: @crypto_coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crypto_coins/1
  # DELETE /crypto_coins/1.json
  def destroy
    @crypto_coin.destroy
    respond_to do |format|
      format.html { redirect_to crypto_coins_url, notice: 'Crypto coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto_coin
      @crypto_coin = CryptoCoin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_coin_params
      params.require(:crypto_coin).permit(:name, :timestamp, :last_price)
    end
end

app/helpers/crypto_coins_helper.rb
module CryptoCoinsHelper
end

app/views/crypto_coins/_form.html.erb
<%= form_with(model: crypto_coin, local: true) do |form| %>
  <% if crypto_coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto_coin.errors.count, "error") %> prohibited this crypto_coin from being saved:</h2>

      <ul>
      <% crypto_coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :timestamp %>
    <%= form.datetime_select :timestamp %>
  </div>

  <div class="field">
    <%= form.label :last_price %>
    <%= form.text_field :last_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crypto_coins/edit.html.erb
<h1>Editing Crypto Coin</h1>

<%= render 'form', crypto_coin: @crypto_coin %>

<%= link_to 'Show', @crypto_coin %> |
<%= link_to 'Back', crypto_coins_path %>

app/views/crypto_coins/index.html.erb
<p id="notice"><%= notice %></p>

<div class ="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>Aca lo importante
          <small>Aca informacion piola</small>
        </h1>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-3">
      <p>Hola!</p>
    </div>
    <div class="col-md-9">
      <canvas id="myChart">
      </canvas>
      <div class="w-100">
      </div>
    </div>
  </div>
  <div class="row" >

    <canvas id="myChart2" >
    </canvas>
  </div>
  <div id="divData" style="display:none">
    <%=@databs_from_database = CryptoCoin.all.select(:last_price).where(market: "BS").order(id: :desc ).limit(30) %>
    <%= last_prices_bitfinex = @databs_from_database.map(&:last_price) %>
    <%=@timestampbs_from_database = CryptoCoin.all.select(:timestamp).where(market: "BS").order(id: :desc ).limit(30)  %>
    <%= timestamps_bitfinex = @timestampbs_from_database.map(&:timestamp)  %>
  </div>




  <script>

      var ctx = document.getElementById("myChart2").getContext('2d');
      var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: <%= raw (timestamps_bitfinex.to_json)%>,
              datasets: [{
                  label: 'Bitfinex',
                  data: <%= raw(last_prices_bitfinex.to_json)%>,
                  backgroundColor: [
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(255, 99, 132, 0.2)',
                  ],
                  borderColor: [
                      'rgba(255,99,132,1)',
                      'rgba(255,99,132,1)',
                      'rgba(255,99,132,1)',

                  ],
                  borderWidth: 1
              }, {
                  label: 'Bitstamp',
                  data: <%= raw (last_prices_bitfinex.to_json)%>,
                  backgroundColor: [
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                  ],
                  borderColor: [
                      'rgba(54, 162, 235, 1)',
                      'rgba(54, 162, 235, 1)',
                      'rgba(54, 162, 235, 1)',

                  ],
                  borderWidth: 1
              }, {
                  label: 'Buda',
                  data: <%= raw (last_prices_bitfinex.to_json)%>,
                  backgroundColor: [
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                  ],
                  borderColor: [
                      'rgba(255, 206, 86, 1)',
                      'rgba(255, 206, 86, 1)',
                      'rgba(255, 206, 86, 1)',

                  ],
                  borderWidth: 1
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero:true
                      }
                  }]
              }
          }
      });
      var ctx1 = document.getElementById("myChart").getContext('2d');
      var myChart2 = new Chart(ctx1, {
          type: 'bar',
          data: {
              labels: [1 ,2, 3],
              datasets: [{
                  label: 'Bitfinex',
                  data: [1, 19, 3],
                  backgroundColor: [
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(255, 99, 132, 0.2)',
                  ],
                  borderColor: [
                      'rgba(255,99,132,1)',
                      'rgba(255,99,132,1)',
                      'rgba(255,99,132,1)',

                  ],
                  borderWidth: 1
              }, {
                  label: 'Bitstamp',
                  data: [12, 1, 3],
                  backgroundColor: [
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                  ],
                  borderColor: [
                      'rgba(54, 162, 235, 1)',
                      'rgba(54, 162, 235, 1)',
                      'rgba(54, 162, 235, 1)',

                  ],
                  borderWidth: 1
              }, {
                  label: 'Buda',
                  data: [ 5, 2, 1],
                  backgroundColor: [
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                  ],
                  borderColor: [
                      'rgba(255, 206, 86, 1)',
                      'rgba(255, 206, 86, 1)',
                      'rgba(255, 206, 86, 1)',

                  ],
                  borderWidth: 1
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero:true
                      }
                  }]
              }
          }
      });

  </script>

  <br>

  <%= link_to 'New Crypto', new_crypto_coin_path %>



</div>

app/views/crypto_coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crypto_coin.name %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @crypto_coin.timestamp %>
</p>

<p>
  <strong>Last price:</strong>
  <%= @crypto_coin.last_price %>
</p>

<%= link_to 'Edit', edit_crypto_coin_path(@crypto_coin) %> |
<%= link_to 'Back', crypto_coins_path %>